---
- name: Set distribution facts
  set_fact:
    _docker_os_dist: "{{ ansible_distribution }}"
    _docker_os_dist_release: "{{ ansible_distribution_release }}"
    _docker_os_dist_major_version: "{{ ansible_distribution_major_version }}"
    _docker_os_dist_check: yes
  tags: ["install", "configure"]

- name: Reinterpret distribution facts for Linux Mint 18
  set_fact:
    _docker_os_dist: "Ubuntu"
    _docker_os_dist_release: "xenial"
    _docker_os_dist_major_version: "16"
  when:
    _docker_os_dist == "Linux Mint" and
    _docker_os_dist_major_version == "18"
  tags: ["install", "configure"]

- include: checks.yml
  tags: ["install", "configure"]

- include: setup-repository.yml
  tags: ["install"]

- include: remove-pre-docker-ce.yml
  when: docker_remove_pre_ce | bool
  tags: ["install"]

- include: install-docker.yml
  tags: ["install"]

- include: setup-audit.yml
  tags: ["configure"]

- include: kernel-3-mount-fixes.yml
  when: ansible_kernel | version_compare('4', '<')
  tags: ["configure"]

- include: configure-docker.yml
  tags: ["configure"]
